services:
  - type: web
    name: TucanaLive
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y chromium
      which chromium || which chromium-browser
      yarn install
      puppeteer install
    startCommand: node index.js